const char *MPDplaylist[47] = {
   "KVOD - 88.1 FM",
   "KCFR - 90.1 FM",
   "KUNC - 91.5 FM",
   "KRCC1 - 91.5 FM",
   "KRCC2 - 91.5 FM",
   "KTCL - 93.3 FM",
   "KPTT - 95.7 FM",
   "KBCO - 97.3 FM",
   "KKMG - 98.9 FM",
   "KOSI - 101.1 FM",
   "KJHM - 101.5 FM",
   "KRFX - 103.5 FM",
   "KBPI - 106.7 FM",
   "KDHT - 107.1 FM",
   "KQKS - 107.5 FM",
   "KHOW - 630 AM",
   "KNUS - 710 AM",
   "KOA - 850 AM",
   "KRWZ - 950 AM",
   "BBC - News: World Service",
   "BBC - News: World Service News",
   "BBC - Radio 1",
   "BBC - Radio 2",
   "BBC - Radio 3",
   "BBC - Radio 4",
   "BBC - Radio 5: Live",
   "BBC - Radio 5: Live Sports Extra",
   "BBC - Radio 6: Music",
   "BBC - Radio 7",
   "BBC - Xtra",
   "SkyRadio - Love",
   "SkyRadio",
   "SkyRadio - NL",
   "SkyRadio - Seasonal",
   "KickRadio",
   "OmroepBrabant",
   "Efteling",
   "Radio 1 - Nieuws24",
   "Radio 1 - Nieuws",
   "Radio 4 - Baroque Around The Clock",
   "Radio 4 - De Klassieken",
   "Radio 4 - Eigentijds",
   "Radio 4 - Film",
   "Radio 4 - Jong Klassiek",
   "Radio 4 - Musica Religiosa",
   "Radio 4 - NPO",
   "Radio 4 - Orgelradio",
};
